import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeProvider from "@/providers/ThemeProvider";
import Layout from "@/components/Layout";
const inter = Inter({ subsets: ["latin"] });
import { Quicksand } from "next/font/google";
import { DataContextApiProvider } from "@/context/DataContextApi";
import { AuthContextProvider } from "@/context/AuthContext";
import { CartContextProvider } from "@/context/CartContext";
import StoreProvider from "@/providers/StoreProvider";
import MyApp from "../providers/Aos";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
  weight: ["300", "400", "500", "600", "700"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <StoreProvider >
          <MyApp>

            <CartContextProvider>
              <DataContextApiProvider>
                <ThemeContextProvider>
                  <ThemeProvider>
                    <div className="container">
                      <Layout>
                        <div>{children}</div>
                      </Layout>
                    </div>
                  </ThemeProvider>
                </ThemeContextProvider>
              </DataContextApiProvider>
            </CartContextProvider>
          </MyApp>
          </StoreProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
